// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1:number,arg2:number,arg3:boolean,arg4:Array<string>,arg5:boolean):Promise<number>;

export function FileDialog():Promise<Array<string>>;

export function GetSizeMB():Promise<number>;
