// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['Convert'](arg1, arg2, arg3, arg4, arg5);
}

export function FileDialog() {
  return window['go']['main']['App']['FileDialog']();
}

export function GetSizeMB() {
  return window['go']['main']['App']['GetSizeMB']();
}
